[package]
name = "lfg-studio/adminservice"
description = "A system that allows admin commands to be registered and triggered by specified admins."
version = "2.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
authors = ["streetrida"]